version: '3.3'

services:
  web:
    build: ./
    command: gunicorn donat_pool.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - ./static:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
    driver: local
  static:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: ./static
