# Generated by Django 4.2.2 on 2023-07-20 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('pkh', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('trusted', models.BooleanField(default=False)),
                ('untrustworthy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Fundraising',
            fields=[
                ('path', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('short_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/fundraisings')),
                ('verified', models.BooleanField(default=False)),
                ('promoted', models.BooleanField(default=False)),
                ('main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraisings', related_query_name='fundraising', to='fundraising.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundraisings', related_query_name='fundraising', to='core.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='fundraising', related_query_name='fundraising', to='core.tag')),
            ],
            options={
                'verbose_name': 'fundraising',
                'verbose_name_plural': 'fundraisings',
            },
        ),
        migrations.CreateModel(
            name='CompletedFundraising',
            fields=[
                ('path', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('targetAmount', models.BigIntegerField()),
                ('raisedAmount', models.BigIntegerField()),
                ('completedAt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_fundraisings', related_query_name='completed_fundraisings', to='fundraising.author')),
            ],
            options={
                'verbose_name': 'completed fundraising',
                'verbose_name_plural': 'completed fundraisings',
            },
        ),
    ]
