# Generated by Django 4.2.2 on 2023-07-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('trusted', models.BooleanField(default=False)),
                ('untrustworthy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='images/categories')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Fundraising',
            fields=[
                ('path', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/fundraisings')),
                ('verified', models.BooleanField(default=False)),
                ('promoted', models.BooleanField(default=False)),
                ('main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraisings', related_query_name='fundraising', to='core.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundraisings', related_query_name='fundraising', to='core.category')),
            ],
            options={
                'verbose_name': 'fundraising',
                'verbose_name_plural': 'fundraisings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fundraisings', models.ManyToManyField(blank=True, related_name='tags', related_query_name='tag', to='core.fundraising')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='CompletedFundraising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetAmount', models.BigIntegerField()),
                ('raisedAmount', models.BigIntegerField()),
                ('completedAt', models.DateTimeField(auto_now_add=True)),
                ('fundraising', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', related_query_name='info', to='core.fundraising')),
            ],
            options={
                'verbose_name': 'completed fundraising',
                'verbose_name_plural': 'completed fundraisings',
            },
        ),
    ]
