# Generated by Django 4.2.2 on 2023-09-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnwantedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Unwanted word',
                'verbose_name_plural': 'Unwanted words',
            },
        ),
    ]
